version: '2'
services:
    teamdojo-app:
        image: teamdojo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://teamdojo-postgresql:5432/teamdojo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    teamdojo-postgresql:
        extends:
            file: postgresql.yml
            service: teamdojo-postgresql
